apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"backend-feed"},"name":"backend-feed","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"backend-feed"}},"template":{"metadata":{"labels":{"app":"backend-feed"}},"spec":{"containers":[{"env":[{"name":"URL","valueFrom":{"configMapKeyRef":{"key":"URL","name":"env-config"}}},{"name":"AWS_BUCKET","valueFrom":{"configMapKeyRef":{"key":"AWS_BUCKET","name":"env-config"}}},{"name":"AWS_REGION","valueFrom":{"configMapKeyRef":{"key":"AWS_REGION","name":"env-config"}}},{"name":"JWT_SECRET","valueFrom":{"configMapKeyRef":{"key":"JWT_SECRET","name":"env-config"}}},{"name":"POSTGRES_DB","valueFrom":{"configMapKeyRef":{"key":"POSTGRES_DB","name":"env-config"}}},{"name":"POSTGRES_HOST","valueFrom":{"configMapKeyRef":{"key":"POSTGRES_HOST","name":"env-config"}}},{"name":"POSTGRES_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"env-secret"}}},{"name":"POSTGRES_USERNAME","valueFrom":{"secretKeyRef":{"key":"POSTGRES_USERNAME","name":"env-secret"}}}],"image":"273543149/udagram-api-feed:v2","imagePullPolicy":"Always","name":"backend-feed","resources":{"limits":{"cpu":"500m","memory":"1024Mi"},"requests":{"cpu":"250m","memory":"64Mi"}},"volumeMounts":[{"mountPath":"/root/.aws/","name":"aws-secret","readOnly":true}]}],"restartPolicy":"Always","volumes":[{"name":"aws-secret","secret":{"secretName":"aws-secret"}}]}}}}
  creationTimestamp: "2023-03-14T02:54:12Z"
  generation: 2
  labels:
    app: backend-feed
  name: backend-feed
  namespace: default
  resourceVersion: "17625"
  uid: d9484c42-b0bf-468c-a71e-58c5b10de051
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend-feed
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-feed
    spec:
      containers:
      - env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              key: URL
              name: env-config
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              key: AWS_BUCKET
              name: env-config
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              key: AWS_REGION
              name: env-config
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              key: JWT_SECRET
              name: env-config
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: env-config
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: env-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: env-secret
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USERNAME
              name: env-secret
        image: 273543149/udagram-api-feed:v2
        imagePullPolicy: Always
        name: backend-feed
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.aws/
          name: aws-secret
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: aws-secret
        secret:
          defaultMode: 420
          secretName: aws-secret
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-14T02:54:12Z"
    lastUpdateTime: "2023-03-14T03:50:06Z"
    message: ReplicaSet "backend-feed-6b89566f9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-14T03:57:11Z"
    lastUpdateTime: "2023-03-14T03:57:11Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  readyReplicas: 2
  replicas: 3
  unavailableReplicas: 1
  updatedReplicas: 3
